import type { StyleAnalysisResult } from "./types";

export function renderStyleAnalysis(result: StyleAnalysisResult): string {
  const lines = [
    `# ${result.title}`,
    "",
    `> Generated by SPARK | Module: style-engine | Profile: ${result.profile}`,
    "",
    `Overall score: **${result.overallScore}/100**`,
    "",
    result.summary,
    "",
    "## Metrics",
    "",
    "| Feature | Value | Target | Score | Note |",
    "| --- | ---: | --- | ---: | --- |",
    ...result.metrics.map(
      (metric) =>
        `| ${metric.label} | ${metric.value} | ${metric.target} | ${metric.score} | ${metric.note} |`,
    ),
    "",
    "## Signals",
    "",
    ...result.signals.map((signal) => {
      const examples = signal.examples.length > 0 ? signal.examples.join(", ") : "none";
      return `- ${signal.label}: ${signal.count} (${examples})`;
    }),
  ];

  if (result.suggestions.length > 0) {
    lines.push("", "## Suggestions", "");
    lines.push(
      ...result.suggestions.map(
        (suggestion) => `- [${suggestion.priority}] ${suggestion.issue}: ${suggestion.action}`,
      ),
    );
  }

  return lines.join("\n");
}
