#!/bin/bash

# ==========================================
# Antigravity Git Auto-Push
# ==========================================
# 用于在 Antigravity (AI) 修改完代码后，一键自动提交并推送到 GitHub。

echo "🚀 [Antigravity] 正在检查代码变动..."

# 检查是否有改动
if [ -z "$(git status --porcelain)" ]; then
    echo "✨ 没有检测到未提交的改动，无需推送。"
    exit 0
fi

# 自动添加所有改动
git add .

# 自动提交，带有专属前缀
git commit -m "feat(ai): updates generated by Antigravity" || true

# 自动推送到当前分支
CURRENT_BRANCH=$(git branch --show-current)
echo "☁️ [Antigravity] 正在推送到远端分支: $CURRENT_BRANCH ..."
git push origin "$CURRENT_BRANCH" || true

echo "🎉 [Antigravity] 提交并推送成功！"
